version: '3.9'
services:

  finance-db:
    image: postgres:15.1
    env_file:
      - _compose/db/local.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  celery:
    image: finance-app
    env_file:
      - _compose/app/local.env
    command: /start-celery-worker
    volumes:
      - .:/app/code
    depends_on:
      - db
      - redis

  celery-beat:
    image: finance-app
    env_file:
      - _compose/app/local.env
    command: /start-celery-beat
    volumes:
      - .:/app/code
    depends_on:
      - db
      - redis

  app:
    image: finance-app
    command: /start-django
    build:
      context: .
      dockerfile: _compose/app/Dockerfile
    depends_on:
      - finance-db
    volumes:
      - .:/app/code
    ports:
      - "8000:8000"
    env_file:
      - _compose/app/local.env

volumes:
  db: